# ===============================
# CONFIGURATION BASE DE DONNEES
# ===============================

spring.datasource.url=jdbc:${INTERNAL_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURATION JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# APPLICATION
# ===============================

spring.application.name=elyo-back
server.port=${PORT:8080}