# ===============================
# CONFIGURATION BASE DE DONNEES
# ===============================

spring.datasource.url=jdbc:h2:file:./data/elyodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONFIGURATION JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# CONSOLE H2
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# APPLICATION
# ===============================

spring.application.name=elyo-back
server.port=8080